# Generated by Django 5.2.5 on 2025-08-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('applicant_name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('resume', models.URLField(blank=True, null=True)),
                ('why_interested', models.TextField()),
                ('product', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.lead')),
            ],
        ),
    ]
